### ISSUE TITLE
Wiki skin tracking

### ISSUE THREAD

**Issue by Kenny2github** [InternationalScratchWiki/ScratchWikiSkin2#35]
- [x] [English](https://en.scratch-wiki.info)
- [x] [German](https://de.scratch-wiki.info)
- [x] [Indonesian](https://id.scratch-wiki.info)
- [x] [Russian](https://ru.scratch-wiki.info)
- [x] [Dutch](https://nl.scratch-wiki.info)
- [x] [Hungarian](https://hu.scratch-wiki.info)
- [x] [Japanese](https://ja.scratch-wiki.info)
- [x] [French](https://fr.scratch-wiki.info)
- [x] [Test](https://test.scratch-wiki.info)

**Comment by Kenny2github** [comment]
Dutch Wiki has the new skin!

**Comment by R4356th** [comment]
@Kenny2github, I am pretty sure that the Hungarian wiki uses the new skin, too.

**Comment by ahmetlii** [comment]
Hungarian Wiki has the new skin - done! @Kenny2github

**Comment by Kenny2github** [comment]
@ahmetlii Translated to Hungarian does not mean they have the skin. The Hungarian wiki is still on the old skin.

**Comment by ahmetlii** [comment]
> @ahmetlii Translated to Hungarian does not mean they have the skin. The Hungarian wiki is still on the old skin.

now in the new skin, we don't need this issue anymore.

**Comment by Kenny2github** [comment]
ALL WIKIS ON NEW SKIN! 🎉
